version: '{build}'
environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '7'
branches:
  only:
    - master
    - /^greenkeeper.*$/
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
platform:
  - x86
  - x64
test_script:
  - yarn run test
build: off
deploy: off
